# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py37, py38, py39, py310, py311, py312, py313

[testenv:py37]
# virtualenv 20.27.0 (released 2024-10-17) dropped Python 3.7 support,
# so by default it installs the latest software versions.
# Manually pinning the compatible software versions re-enables py37 tests.
setenv =
    VIRTUALENV_NO_SETUPTOOLS = 1

[testenv]
commands = python -m unittest discover
deps =
    packaging
    setuptools; python_version < "3.8"