name: Make Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload build to action .tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: build_items
          path: dist/**

  upload_to_tag:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Download build
          uses: actions/download-artifact@v2
          with:
            name: build_items
            path: build

        - name: Pack build to build.zip
          run: |
            zip -r build.zip build/

        - name: Add files to tag and make release
          uses: ncipollo/release-action@v1.13.0
          with:
            artifacts: "build/*.tar.gz, build/*.whl"
            allowUpdates: true
        # Use always() to always run this step to publish test results when there are test failures
  upload_to_pypi:
    needs: upload_to_tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build_items
          path: build
      - name: Add random numbers to filenames
        run: |
          cd build
          for file in *.tar.gz; do mv "$file" "${file%.tar.gz}-$RANDOM.tar.gz"; done
          for file in *-py2.py3-none-any.whl; do mv "$file" "${file%-py2.py3-none-any.whl}-$RANDOM-py2.py3-none-any.whl"; done
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: build/
          skip-existing: true